### ISSUE TITLE
Scripts and styles are not aggregated in the root WebC layout template

### ISSUE THREAD

**Issue by darthmall** [11ty/eleventy-plugin-webc#11]
If you’re using WebC for layout templates, you can’t put WebC components in the layout that calls `this.getCSS` or `this.getJS` and have its styles and scripts be aggregated.

Let me know if you’d like a repo with a reproduction of the issue.

### site-footer.webc

```html
<footer>
  <p>&copy; 2022 Yours Truly</p>
</footer>
<style>
  footer {
    font-family: fantasy;
  }
</style>
```

### base.webc

```html
<!doctype html>
<html>
<head>
  <style @html="this.getCSS(this.page.url)"></style>
</head>
<body>
  <site-footer webc:nokeep></site-footer>
</body>
</html>
```

### Output

```html
<!doctype html>
<html>
<head>
  <style></style>
</head>
<body>
  <footer>
    <p>&copy 2022 Yours Truly</p>
  </footer>
</body>
</html>
```

Note the empty `<style>` tag.

## Workaround

You can work around this issue by adding a template in the layout chain so that you aren't including styled components in your root layout template.

### root.webc

```html
<!doctype html>
<html>
<head>
  <style @html="this.getCSS(this.page.url)"></style>
</head>
<body @html="this.content"></body>
</html>
```

### base.webc

```html
---
layout: root.webc
---
<site-footer webc:nokeep></site-footer>
```

**Comment by kellenmace** [comment]
Confirming that I'm encountering similar issues. When I follow along with the [Crash Course in Eleventy’s new WebC Plugin](https://www.youtube.com/watch?v=X-Bpjrkz-V8) YouTube video and insert `<style @html="this.getCSS(this.page.url)"></style>` into the `layout.webc` file, then build the site, I get an empty line where the aggregated styles should appear, like this:

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    
  </head>
  <body><my-component>HELLO I AM A COMPONENT
</my-component></body>
</html>
```

**Comment by oliverjam** [comment]
The nested layouts workaround doesn't appear to work any more. @zachleat is it possible that the https://github.com/11ty/eleventy/issues/2654 fix stopped this working? Since nested WebC layouts are correctly treated as layouts now.

Given that layouts ideally need to support bundling, is there a better solution than disabling it for only the root layout (assuming 11ty knows which one that is). This would be awkward but at least documentable as a way to bundle components that are used in layouts.

**Comment by zachleat** [comment]
Shipping this with Eleventy WebC v0.8.0 (likely Monday).

More details in #33

**Comment by zachleat** [comment]
Eleventy WebC v0.8.0 is out!
