### ISSUE TITLE
Make `components` relative to custom `input` directory

### ISSUE THREAD

**Issue by 5t3ph** [11ty/eleventy-plugin-webc#12]
Based on a hang-up I had trying to use WebC for the first time, wherein it was not described that updating the `components` location would be _root_ relative and not adjust if the config changed the `input` directory.

**Current behavior**
`components` directory is root-relative

**Desired behavior**
`components` directory is `input` directory relative (or flexible for both?)

**Temp fix**
Include a note in the docs that this path is root-relative

**Comment by zachleat** [comment]
I don’t think you want to put your `webc` _components_ in your input directory as they’ll be double processed as both Eleventy pages and inside of Eleventy pages.

Notably, you _can_ make it work okay with `eleventyConfig.ignores` https://www.11ty.dev/docs/ignores/#configuration-api though!

I’ll amend the docs!

**Comment by zachleat** [comment]
It’s live, thank you! https://www.11ty.dev/docs/languages/webc/#global-no-import-components
