### ISSUE TITLE
WebC props - how to use?

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy-plugin-webc#23]
In the WebC docs, the attributes discussion starts here: https://www.11ty.dev/docs/languages/webc/#attributes-and-webcroot. Scrolling down to Properties, https://www.11ty.dev/docs/languages/webc/#props-(properties), it describes how to pass a property to a webc by using @propname. But how would the component access the property? I don't see that documented.

**Comment by zachleat** [comment]
Example deploying to https://www.11ty.dev/docs/languages/webc/#props-(properties)

and on https://github.com/11ty/webc#properties-or-props

**Comment by cfjedimaster** [comment]
This helps a LOT, thank you VERY MUCH!
