### ISSUE TITLE
Preprocess Markdown with Webc to have an MDX syntax

### ISSUE THREAD

**Issue by seb-celinedesign** [11ty/eleventy-plugin-webc#26]
Hi,
I'm trying to preprocess Markdown with Webc, which would be awesome : kind of a MDX syntax no ?
So i set the markdownTemplateEngine config to webc, but 11ty isn't compiling my component. 😢
At the moment, I've to preprocess with `Liquid` and use the `EleventyRenderPlugin` : `{% renderTemplate "webc" %}`
Not very straightforward imho…

It'll be great if the markdownTemplateEngine config was able to use webc.

**Comment by zachleat** [comment]
It seems _risky_ to me to pre-parse Markdown as HTML but it _might_ work? I’m not sure!

Are you saying that `markdownTemplateEngine: "webc"` did not work? In my tests it seems to be doing it’s thing

**Comment by zachleat** [comment]
![image](https://user-images.githubusercontent.com/39355/199598910-daa2d708-d7ce-449c-9765-c0ca60840118.png)

**Comment by seb-celinedesign** [comment]
Thx Zach,
Let me check again my code…

**Comment by seb-celinedesign** [comment]
👍 Ok it works perfectly when you do NOT put the `markdownTemplateEngine` directive in the dir config like me : 
```
return {
  dir: {
    input: 'src/client/templates',
    markdownTemplateEngine: 'webc',
  }
};
```
🤯
Thx Zach.
I'm going to bed…
