### ISSUE TITLE
Dynamic permalinks and WebC

### ISSUE THREAD

**Issue by voxpelli** [11ty/eleventy-plugin-webc#27]
When using liquid I had a `news.11tydata.json` containing:

```json
{
  "layout": "layouts/post",
  "tags": ["news"],
  "permalink": "{{ page.date | date: '%Y/%m' }}/{{ title | slug }}/index.html"
}
```

When using WebC [I should instead be using WebC](https://www.11ty.dev/docs/permalinks/#use-template-syntax-in-permalink) for that? Feels like a challenge? I would preferably use eg. liquid for my permalinks and only WebC for my actual HTML

> You may use data variables here (and template syntax, too). These will be parsed with the current template’s rendering engine.

This plugin could provide a custom behavior by setting `permalink` in `compilerOptions` to a function or `false`: https://github.com/11ty/eleventy-plugin-webc/blob/f7bc146888a15f7e057570ffa40bc1c65daf1a09/src/eleventyWebcTemplate.js#L84-L90

I think it should done of:

1. Have an example of a dynamic permalink in WebC
2. Provide an alternative renderer for permalinks
3. Disable permalink link rendering if its not feasible with WebC

**Comment by voxpelli** [comment]
Some progress on `1.`:

```json
  "permalink": "<div webc:nokeep @text='`subdir/${slugify(title)}/index.html`'></div>"
```

**Comment by zachleat** [comment]
Yeahhhhhh… this is a hefty bug—sorry. But easily fixable. I just need to map the dynamic attribute JavaScript parsing code to the Eleventy Custom template permalink stuff: https://www.11ty.dev/docs/languages/custom/#compileoptions.permalink-to-override-permalink-compilation

**Comment by zachleat** [comment]
This will ship with Eleventy WebC 0.7.0

**Comment by rijkvanzanten** [comment]
Glad to see my workaround for https://github.com/11ty/eleventy/issues/2615 is no longer needed 😄
