### ISSUE TITLE
Add global filters as WebC Helpers

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-plugin-webc#3]
Wire up https://www.11ty.dev/docs/filters/#universal-filters to https://github.com/11ty/webc#helper-functions

**Comment by seb-celinedesign** [comment]
Hi Zach,

Is it what's needed for using 11ty image plugin in WebC file ?

**Comment by zachleat** [comment]
@seb-celinedesign not quite! I just filed this one https://github.com/11ty/eleventy-plugin-webc/issues/10 and I’ll try to get an example of this use case for y’all!
