### ISSUE TITLE
Persist page-specific bundles to the file system to make use of browser cache

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-plugin-webc#4]
https://github.com/11ty/eleventy-plugin-webc#css-and-js-bundler-mode but I want the deferred bucket to write to the file system (and the layout file reference the file’s URL) to make use of the browser cache.

Requested by https://twitter.com/techytacos/status/1575143767484481537 and https://twitter.com/the_ross_man/status/1574864528268992514

**Comment by zachleat** [comment]
https://github.com/11ty/eleventy-plugin-bundle#write-a-bundle-to-a-file has this!

Related #48

**Comment by douglas-johnson** [comment]
I would like to use this feature, but I think I must be misunderstanding something. What am I doing wrong here?

I have this is my layout.webc file:
`<link rel="stylesheet" type="text/css" :href="getBundleFileUrl('css')" webc:keep />`

But I don't get a CSS file in my `_site` folder or any value for href. The output is: `<link rel="stylesheet" type="text/css" href="">`

My related depedencies are:
```json
{
"@11ty/eleventy": "^2.0.0",
"@11ty/eleventy-plugin-webc": "^0.8.1",
"@11ty/eleventy-fetch": "^3.0.0",
"@11ty/eleventy-plugin-bundle": "^1.0.1"
}
```

**Comment by zachleat** [comment]
Ah, sorry—this requires WebC v0.9.0 which will ship today.
