### ISSUE TITLE
Set frontmatter from within component's <script> tag

### ISSUE THREAD

**Issue by georgedoescode** [11ty/eleventy-plugin-webc#45]
We can currently update frontmatter within a `.webc` page like this: 

```
---js
{
  layout: "my-layout.webc",
  title: "My page title",
  currentDate: function() {
    // You can have a JavaScript function here!
    return (new Date()).toLocaleString();
  }
}
---
```

It would be great if we could also do this within a component's `<script>` tag!

**Comment by zachleat** [comment]
Just for me, this is useful to set eleventy configuration properties to the data cascade (permalink, pagination, etc):

https://www.11ty.dev/docs/data-configuration/

Marginally related to https://github.com/11ty/webc/issues/109

**Comment by zachleat** [comment]
https://fediverse.zachleat.com/@zachleat/109883407524691666

**Comment by zachleat** [comment]
https://github.com/11ty/demo-eleventy-js-front-matter has the demo of this in action!

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/data-frontmatter-customize/#example-use-javascript-in-your-front-matter is the new home on the docs. I think we’ll attempt to roll with this for a bit and see if it’s sufficient before we go forward with a special `<script>` in WebC to populate the data cascade
