### ISSUE TITLE
Asset bundling outside webc, and non layout files

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy-plugin-webc#46]
I was testing asset bundling with a Liquid file and noticed this didn't work:

```
<script>{{ page.url | webcGetJs }}</script>
```

No error was thrown, it just returned an empty script tag. On a whim, I moved my HTML layout from my test file to a layout, and it worked there. Now, the docs do say:

```
Outside of *.webc files (e.g. in Nunjucks or Liquid layout files)
```

and "layout" is specified there, I don't see why it couldn't work in a regular Liquid page using the same code. 

If this can't be done, can we bold the layout part perhaps, or make it more clear?

**Comment by cfjedimaster** [comment]
I'll add, the fact that in a *non-layout* webc file it works, really implies it should work in a non-layout liquid/etc file as well.

**Comment by zachleat** [comment]
This is solved with https://github.com/11ty/eleventy-plugin-bundle and will be used internally in the eleventy-webc-plugin@0.9.0 (please subscribe to #48!)
