### ISSUE TITLE
Question whey pass props and not attribute

### ISSUE THREAD

**Issue by SteveALee** [11ty/eleventy-plugin-webc#6]
I'm probably guilty of not knowing all the details but in your [interactive WebC video](https://youtu.be/p0wDUK0Z5Nw?t=398) you pass a prop.

```javascript
  <my-counter @value="10"></my-counter>
``` 

Would a standard attribute not be more "platformy"?

```javascript
  <my-counter value="10"></my-counter>
``` 

You quote it like it's an attribute. I guess the  '@' just stands out to me and implies the compiler gets involved for some reason.

I know the platform relationship between properties and attribs gets messy in places and is arguably a design problem, so is that why you use a property, with the '@' 'syntax? IE Is this a WebC specific way of passing props into a component, sidestepping attributes?

**Comment by zachleat** [comment]
Yeah! Good question!

If you want `value` to appear in your output HTML, use an attribute! If you want `value` to only be visible to WebC and to _hide it_ from the output HTML, prefix it with `@` as a prop: `@value`. 

They are functionally the same but props do not appear in your output HTML.
