### ISSUE TITLE
Modifying webc components does not cause a site rebuild

### ISSUE THREAD

**Issue by mvllow** [11ty/eleventy-plugin-webc#62]
I was converting an 11ty site from njk to webc in several places and noticed when editing webc components, the site was not rebuilt. My personal project was using `./content` as the input directory and a custom `./content/_components/**/*.webc` components directory. A minimal reproduction repo is included with the same issue happening using the default config. Apologies if I missed anything. Thanks!

**Reproduction**

> https://github.com/mvllow/11ty-webc-no-rebuild-repro

1. Install dependencies and run development server
   ```sh
   npm install && npm run dev
   ```
2. Modify `_components/my-header.webc`
3. Changes will not be applied until manually restarting the server

**Comment by janmonschke** [comment]
A bugfix for this will be shipped with 2.0.2. Check out this related issue in the eleventy repo: https://github.com/11ty/eleventy/issues/2903

**Comment by zachleat** [comment]
Thanks @janmonschke—please follow along at https://github.com/11ty/eleventy/issues/2903!
